DZ/HomeWork/HomeWork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls'))
]

DZ/HomeWork/library/urls.py
from django.urls import path
from . import views


app_name = 'library'
urlpatterns = [
    path('', views.book, name ="home"),
    path('report/',views.report, name = "report"),
    path('post/', views.post, name="post"),
]

DZ/HomeWork/library/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    name = models.CharField('Название поставщика ' ,max_length=50)
    field = models.CharField('Поставляемый продукт ' ,max_length=500)
    def __str__(self):
        return self.name

class Library(models.Model):
    name = models.CharField('Название библиотеки' ,max_length=50)
    number = models.CharField('Контактный номер' ,max_length=50, default=1)
    Post = models.ManyToManyField(Post, blank=True)
    def __str__(self):
        return self.name

class Book(models.Model):
    library = models.ForeignKey(Library, on_delete=models.CASCADE)
    name = models.CharField('Название книги',max_length=50)
    quantity = models.IntegerField('Количество' ,max_length=1000)
    author = models.CharField('Автор' ,max_length=50)
    description = models.CharField('Описание' ,max_length=1000)
    def __str__(self):
        return self.name

DZ/HomeWork/library/views.py
import operator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post,Library,Book
from django.urls  import reverse

def index(request):
    book_list = Library.objects.all()
    context = {'book_list': book_list}
    return render(request, 'library/main.html', context)

def book(request):
    book = Book.objects.all().select_related('library')
    libraries = Library.objects.all()
    librarystr = []
    for d in libraries:
        librarystr.append(d)
    order = {key: i for i, key in enumerate(librarystr)}
    book_list = sorted(book, key=lambda book: order.get(book.library, 0))
    return render(request, 'library/main.html',{'book_list': book_list})

def report(request):
    book = Book.objects.all().select_related('library')
    libraries = Library.objects.all()
    librarystr = []
    for d in book:
        librarystr.append(d)
    order = {key: i for i, key in enumerate(librarystr)}
    book_list = sorted(book, key=lambda book: order.get(book.library, 0))
    return render(request, 'library/view.html',{'book_list': book_list})

def post(request):
    libraries = Library.objects.all().prefetch_related('Post')
    return render(request, 'library/supply.html',{'libraries': libraries})

DZ/HomeWork/library/templates/library/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark style="background-color: #e3f2fd;" rounded" aria-label="Twelfth navbar example">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
          <ul class="nav nav-tabs ">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'library:home'%}"'>Библиотеки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'library:post' %}"'>Издание</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'library:report' %}"'>Отчет</a>
                </li>
          </ul>
        </div>
      </div>
    </nav>
{% block content %}{% endblock %}
</body>
</html>

DZ/HomeWork/library/templates/library/main.html
{% extends 'library/base.html' %}

{% block title %}
Главная страница
{% endblock %}
{% block content %}
        <div class="container ">
                {% for model in book_list %}
                <div class="col mt-4">
                    <div class="card shadow">
                        <div class="card-body">
                            <h3 class="p-1 mb-0 card-title mx-auto text-center">{{ model.library.name }}</h3>
                            <h5 class="p-1 mx-auto text-center">{{model.name}}</h5>
                            <p><strong>В наличии:</strong><span class="font-monospace "> {{model.quantity}} книги</span></p>
                            <p><strong>Автор:</strong> <span class="font-monospace "> {{model.author}}</span></p>
                            <p><strong>Описание:</strong> <span class="font-monospace ">{{model.description}}</span></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
        </div>
{% endblock %}

DZ/HomeWork/library/templates/library/supply.html
{% extends 'library/base.html' %}

{% block title %}
Поставщики
{% endblock %}
{% block content %}
        <div class="container">
                {% for d in libraries %}
                    <div class="card shadow ">
                        <div class="card-body">
                            <h5 class="p-3 mb-0 bg-primary text-white card-title mx-auto text-center">{{ d.name }}</h5>
                            <p class = "p-2 mb-auto mx-auto text-center"><strong>Контактный номер библиотеки:</strong> {{d.number}}</p>
                            <div class="mb-0 mx-auto ">
                                {% for model in d.Post.all %}
                                <p class = "p-1 mb-0 bg-success text-white mx-auto text-center"><strong class="pb-1 ">Поставщик: {{ model.name }}</strong></p>
                                    <p class = "ps-2 mb-1 mx-auto text-center"><strong class="pb-1 ">Поставляемый продукт:</strong> {{ model.field }}</p>
                                {% endfor %}
                            </div>
                            </p>
                        </div>
                    </div>
                {% endfor %}
        </div>
{% endblock %}

DZ/HomeWork/library/templates/library/view.html
{% extends 'library/base.html' %}

{% block title %}
Отчеты
{% endblock %}

{% block content %}
<div class ="container">
    <h1>Отчет о библиотеках: {{ header }}</h1>
    {% if book_list %}
        <table class="table table-hover table-bordered border-dark table-sm mx-auto">
            <tr class="text-center "><th>Название книги</th><th>Библиотека</th><th>Номер библиотеки</th><th>Автор</th><th>Количество книг</th><th>Описание</th></tr>
            {% for model in book_list %}
                <tr class="text-center"><td>{{ model.name }}</td><td>{{ model.library }}</td><td>{{ model.library.number }}</td><td>{{ model.author }}</td>
                <td>{{ model.quantity }}</td><td>{{ model.description }}</td></tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Database is empty.</p>
    {% endif %}
</div>

{% endblock %}